CREATE TABLE IF NOT EXISTS accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50),
    email VARCHAR(254),
    password_hash VARCHAR(255) NULL,
    signed_in_with_google BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);