services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=AccountDB'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=tp067551'
    ports:
      - '5432'
